#server服务参数配置
server:
  port: 7520                #服务端口
  tomcat:
    uri-encoding: UTF-8     #指定tomcat的编码格式

#spring参数配置
spring:
  application:
    name: kindcloud-zuul    #指定服务名
  profiles:
    active: dev             #dev表示为开发环境,使用配置文件application-dev

#注册中心参数配置
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 20             #心跳频率,默认30秒
    leaseExpirationDurationInSeconds: 60          #心跳超时时间,默认为90秒
    preferIpAddress: true                         #将IP注册到Eureka Server上,默认机器的主机名
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: ${kindcloud.eureka.url}

#路由参数配置
zuul:
  routes:
    kindcloud-sys:
      path: /sys/**
      service-id: kindcloud-sys
    host:
      connect-timeout-millis: ${etcloud.ConnectTimeout}
      socket-timeout-millis: ${etcloud.ReadTimeout}