#server服务参数配置
server:
  port: 7530                #服务端口
  tomcat:
    uri-encoding: UTF-8     #指定tomcat的编码格式

#spring参数配置
spring:
  application:
    name: kindcloud-sys     #指定服务名
  profiles:
    active: dev             #dev表示为开发环境,使用配置文件application-dev
  datasource:
    name: test
    url: ${kindcloud.datasource.url}
    username: ${kindcloud.datasource.username}
    password: ${kindcloud.datasource.password}
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource                # 使用alibaba数据库连接池
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

#注册中心参数配置
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 20             #心跳频率,默认30秒
    leaseExpirationDurationInSeconds: 60          #心跳超时时间,默认为90秒
    preferIpAddress: true                         #将IP注册到Eureka Server上,默认机器的主机名
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: ${kindcloud.eureka.url}

#mybatis参数配置
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: top.aries.kind.model

#LogBack日志参数配置
logging:
  path: /data/kindcloud/logs
  config: classpath:config/logback-spring.xml
  log-level: INFO