/*
 * MainFrm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.java1234.view;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author  __USER__
 */
public class MainFrm extends JFrame {

	/** Creates new form MainFrm */
	public MainFrm() {
		initComponents();
		// �������
		this.setExtendedState(JFrame.MAXIMIZED_BOTH);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		table = new javax.swing.JDesktopPane();		//分层面板
		jMenuBar1 = new javax.swing.JMenuBar();		//菜单栏
		jMenu1 = new javax.swing.JMenu();			//菜单
		jMenu3 = new javax.swing.JMenu();
		jmiBookTypeAdd = new javax.swing.JMenuItem();	//菜单项
		jmiBookTypeManage = new javax.swing.JMenuItem();
		jMenu4 = new javax.swing.JMenu();
		jmiBookAdd = new javax.swing.JMenuItem();
		jmiBookManage = new javax.swing.JMenuItem();
		jmiExit = new javax.swing.JMenuItem();
		jMenu2 = new javax.swing.JMenu();
		jmiaboutJava1234 = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);	//关闭选项
		setTitle("图书管理系统主界面");		//标题

		jMenu1.setIcon(new javax.swing.ImageIcon(
				"C:\\Users\\caofeng\\Desktop\\images\\base.png")); // NOI18N
		jMenu1.setText("基本数据维护");

		jMenu3.setIcon(new javax.swing.ImageIcon(
				"C:\\Users\\caofeng\\Desktop\\images\\bookTypeManager.png")); // NOI18N
		jMenu3.setText("图书类别管理");

		jmiBookTypeAdd.setIcon(new javax.swing.ImageIcon(
				"C:\\Users\\caofeng\\Desktop\\images\\add.png")); // NOI18N
		jmiBookTypeAdd.setText("添加图书类别");
		jmiBookTypeAdd.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jmiBookTypeAddActionPerformed(evt);
			}
		});
		jMenu3.add(jmiBookTypeAdd);

		jmiBookTypeManage.setIcon(new javax.swing.ImageIcon(
				"C:\\Users\\caofeng\\Desktop\\images\\edit.png")); // NOI18N
		jmiBookTypeManage.setText("图书类别维护");
		jmiBookTypeManage
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jmiBookTypeManageActionPerformed(evt);
					}
				});
		jMenu3.add(jmiBookTypeManage);

		jMenu1.add(jMenu3);

		jMenu4.setIcon(new javax.swing.ImageIcon(
				"C:\\Users\\caofeng\\Desktop\\images\\bookManager.png")); // NOI18N
		jMenu4.setText("图书管理");

		jmiBookAdd.setIcon(new javax.swing.ImageIcon(
				"C:\\Users\\caofeng\\Desktop\\images\\add.png")); // NOI18N
		jmiBookAdd.setText("添加图书");
		jmiBookAdd.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jmiBookAddActionPerformed(evt);
			}
		});
		jMenu4.add(jmiBookAdd);

		jmiBookManage.setIcon(new javax.swing.ImageIcon(
				"C:\\Users\\caofeng\\Desktop\\images\\edit.png")); // NOI18N
		jmiBookManage.setText("图书维护");
		jmiBookManage.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jmiBookManageActionPerformed(evt);
			}
		});
		jMenu4.add(jmiBookManage);

		jMenu1.add(jMenu4);

		jmiExit.setIcon(new javax.swing.ImageIcon(
				"C:\\Users\\caofeng\\Desktop\\images\\exit.png")); // NOI18N
		jmiExit.setText("退出系统");
		jmiExit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jmiExitActionPerformed(evt);
			}
		});
		jMenu1.add(jmiExit);

		jMenuBar1.add(jMenu1);

		jMenu2.setIcon(new javax.swing.ImageIcon(
				"C:\\Users\\caofeng\\Desktop\\images\\about.png")); // NOI18N
		jMenu2.setText("关于我们");

		jmiaboutJava1234.setIcon(new javax.swing.ImageIcon(
				"C:\\Users\\caofeng\\Desktop\\images\\me.png")); // NOI18N
		jmiaboutJava1234.setText("\u5173\u4e8eJava1234");
		jmiaboutJava1234.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jmiaboutJava1234ActionPerformed(evt);
			}
		});
		jMenu2.add(jmiaboutJava1234);

		jMenuBar1.add(jMenu2);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(table,
				javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(table,
				javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jmiaboutJava1234ActionPerformed(java.awt.event.ActionEvent evt) {
		AboutJava1234InterFrm aboutJava1234InterFrm = new AboutJava1234InterFrm();
		aboutJava1234InterFrm.setVisible(true);
		this.table.add(aboutJava1234InterFrm);
	}

	private void jmiBookManageActionPerformed(java.awt.event.ActionEvent evt) {
		BookManageInterFrm BookManageInterFrm = new BookManageInterFrm();
		BookManageInterFrm.setVisible(true);
		this.table.add(BookManageInterFrm);
	}

	private void jmiBookAddActionPerformed(java.awt.event.ActionEvent evt) {
		BookAddInterFrm BookAddInterFrm = new BookAddInterFrm();
		BookAddInterFrm.setVisible(true);
		this.table.add(BookAddInterFrm);
	}

	private void jmiBookTypeManageActionPerformed(java.awt.event.ActionEvent evt) {
		BookTypeManageInterFrm BookTypeManageInterFrm = new BookTypeManageInterFrm();
		BookTypeManageInterFrm.setVisible(true);
		this.table.add(BookTypeManageInterFrm);
	}

	private void jmiBookTypeAddActionPerformed(java.awt.event.ActionEvent evt) {
		BookTypeInterFrm bookTypeInterFrm = new BookTypeInterFrm();
		bookTypeInterFrm.setVisible(true);
		this.table.add(bookTypeInterFrm);
	}

	private void jmiExitActionPerformed(java.awt.event.ActionEvent evt) {
		int result = JOptionPane.showConfirmDialog(null, "�Ƿ��˳�ϵͳ");
		if (result == 0) {
			this.dispose();
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainFrm().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenu jMenu3;
	private javax.swing.JMenu jMenu4;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jmiBookAdd;
	private javax.swing.JMenuItem jmiBookManage;
	private javax.swing.JMenuItem jmiBookTypeAdd;
	private javax.swing.JMenuItem jmiBookTypeManage;
	private javax.swing.JMenuItem jmiExit;
	private javax.swing.JMenuItem jmiaboutJava1234;
	private javax.swing.JDesktopPane table;
	// End of variables declaration//GEN-END:variables

}