#server服务参数配置
server:
  port: 7560                #服务端口
  tomcat:
    uri-encoding: UTF-8     #指定tomcat的编码格式

#spring参数配置
spring:
  application:
    name: kindcloud-server   #指定服务名
  profiles:
    active: dev             #dev表示为开发环境,使用配置文件application-dev

#注册中心参数配置
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 20             #心跳频率,默认30秒
    leaseExpirationDurationInSeconds: 60          #心跳超时时间,默认为90秒
    preferIpAddress: true                         #将IP注册到Eureka Server上,默认机器的主机名
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:7510/eureka/