eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 20
    leaseExpirationDurationInSeconds: 60
  client:
    serviceUrl:
      defaultZone: http://localhost:7510/eureka/

license.enable: false
license.registerKey: "abcdefghijklmnopqrstuvwxyz123456"
license.serverLicCode: "6dH7aVC5PsZfYaf7/Qodvthz09bzPuTIXAjqz/8a4crN1tqibd5HkbLaqULE01pOl5R3ZgXbSYL6\r\nFFuMhrhNKiwWviAnjE0ANuCxUUlo39VdsbfaDb1HWQ==9UXkpiJxR91hu8ZaUzzbFg=="